### ISSUE TITLE
Regression in 8.x: canvas size no longer adjusts with available space

### ISSUE THREAD

**Issue by stefanb2** [elraccoone/react-unity-webgl#114]
**Describe the bug**
We're trying to move to an Unity 2020.1 build. Therefore I upgraded to v8.x and made the necessary changes to the application.

One of our Unity components is wrapped together with another (optional) `div` in a parent that covers the whole window. The 2nd div is rendered dynamically based on its React component visibility state (think of a side-bar pop-up window), i.e. roughly this structure:

```js
<div
  style={{
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    width: '100%',
  }}
>
  <Unity unityContext={...} width="100%" height="100%" />
  {<div .... > .... some content ... </div>} // or "null" when invisible...
</div>
```

* 2nd div not rendered: resizing the browser works nicely, i.e. the Unity canvas always resizes to the available space
* 2nd div rendered: canvas width does not change
   * i.e. the browser renders a horizontal scroll bar and both elements are rendered side-by-side
   * this forces the user to scroll to the right to make the contents of the 2nd div visible.
   * in the example I'm looking at I see in the browser element inspector `<canvas width="1272" ... >`
   * if I now change the the width in the inspector manually to some value between 0 to 820 then the canvas recalculates to `width="821"`, which is apparently the correct size to display the canvas and the 2nd div without a horizontal scroll bar
   * when I close the 2nd div again, the canvas recalculates again to `width="1272"` and thus fills the width of the window again
   * as far as I can tell only the case of shrinking the canvas width automatically isn't working

**Expected behavior**
Unity canvas should resize to available space in the parent

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser: Chromium 84

**Additional context**
This worked without problems for the same web app/Unity components using an Unity 2019 build and 7.x.

I first thought that this might be caused that the enabling of the 2nd div doesn't trigger a re-render of the `Unity` component. But even after changing the code to ensure a re-render, the canvas size is not adjusted. I think this is because there are no prop changes as the width/height are hard-coded to 100%, i.e. either React or `react-unity-webgl` doesn't consider this a "component has been updated" case.

* I also tried `<Unity width="auto" ... >` but then the canvas no longer resizes when I make the browser window wider. It stays at the original width and the right hand side of the browser window is a blank white space.
* `<Unity width="-webkit-fill-available" ... >` seems to behave like the 100% variant.

**Comment by jeffreylanters** [comment]
I'm not quite sure if I understand what you're saying. The previous implementation was kind of unstable due to the way Unity implemented canvas scaling (see #47). In the current build all the Unity component renders is a single Canvas element without being wrapped in any other elements. This way the developer has full control over the scaling of the canvas. -- By default the size is 800px in width by 600px in height, this can indeed be altered using the props. But besides the height and width prop no other factors influence the canvas's size.

**Comment by jeffreylanters** [comment]
Previously the Unity instance was being instantiated using a [width and height of 100%](https://github.com/elraccoone/react-unity-webgl/blob/7174b9e7b3a535b40d9e46caaafcd690b9e695ff/source/components/Unity.ts#L116), these would be assigned to the canvas itself. And the canvas would be wrapped inside of a htmlDivElement with the [width and height styling](https://github.com/elraccoone/react-unity-webgl/blob/7174b9e7b3a535b40d9e46caaafcd690b9e695ff/source/components/Unity.ts#L143) which is roughly the same code as [the current build's styling](https://github.com/elraccoone/react-unity-webgl/blob/c488026249459901e2b590e26df0259fdbd42759/source/components/unity.ts#L79).

**Comment by stefanb2** [comment]
The element inspector shows `style="width: 100%..."`  but additionally there are `width=` and `height=` attributes that show the canvas size in pixels. Those get updated e.g. on browser window resize.When I wrote "I update the width manually" I updated the `width=` attribute on the canvas, not the width property in the `style=` attribute.

As far as I can tell from the code I can't control the `width=` and `height=` attributes of the canvas element. 

What my testing shows is that those attributes do not get updated when a 2nd div is rendered into the same parent div that wraps the canvas and the 2nd div element.

**Comment by stefanb2** [comment]
I'll try tomorrow what happens if I re-wrap the 8.x canvas with a `<div>` like 7.x did.

**Comment by stefanb2** [comment]
Thanks for pointing out the implementation differences between 7.x and 8.x. To be honest I would have probably never thought of comparing the 7.x generated DOM with the one from 8.x and noticed this difference. In the future it might be worthwhile to add an upgrading section to the wiki which mentions such differences.

To whom it may concern: I restored the resizing functionality in our use case with the following code:
```js
<div
  style={{
    width: '100%',
    height: '100%',
  }}
>
  <Unity unityContext={...} width="100%" height="100%" />
</div>
```
As far as I can tell now the resizing with 8.x/Unity 2020.1 behaves exactly the same as with 7.x/Unity 2019: the canvas automatically shrinks when another `<div>` element is added to the same parent `<div>` element that also contains the `Unity` component.

**Comment by stefanb2** [comment]
BTW: such an upgrade page might also be the right place to mention that the `resized` event has been removed.

**Comment by jeffreylanters** [comment]
Thanks you. I've updated the [documentation](https://github.com/elraccoone/react-unity-webgl/wiki/Communication-Unity-on-Resize)
