### ISSUE TITLE
How to solve the problem of cros？

### ISSUE THREAD

**Issue by MrJiDong** [elraccoone/react-unity-webgl#117]
I want to load models remotely and my site allows cross domain。
![QQ图片20200903153558](https://user-images.githubusercontent.com/48897264/92085331-40ebf080-edfb-11ea-8cf4-a81b640e176f.png)

**Comment by jeffreylanters** [comment]
Hi. Sorry, this is too off-topic.

https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

**Comment by MrJiDong** [comment]
Oh, the reason for chrome.
