### ISSUE TITLE
UnityContext is not a constructor.

### ISSUE THREAD

**Issue by michaelcuneo** [elraccoone/react-unity-webgl#118]
**Describe the bug**

Using the sample code, with the name of my Unity project changed, I get 

Uncaught (in promise) TypeError: react_unity_webgl__WEBPACK_IMPORTED_MODULE_3__.UnityContext is not a constructor.

**Comment by jeffreylanters** [comment]
Maybe there is something wrong compiler settings, what are you using? Babel, Typescript?

See source: [unityContext.ts](https://github.com/elraccoone/react-unity-webgl/blob/5a0c3c14093434a320cea8e25b6f10a54750fa18/source/models/unityContext.ts#L32)
```ts
  /**
   * Creates a new instance of the Unity context model.
   * @param {IUnityConfig} unityConfig The Unity config used to build the player.
   */
  constructor(public unityConfig: IUnityConfig) {
    if (typeof (window as any).ReactUnityWebGL === "undefined")
      (window as any).ReactUnityWebGL = {};
  }
```

**Comment by michaelcuneo** [comment]
Oh, I need TypeScript for this?

**Comment by jeffreylanters** [comment]
No, it's both JavaScript and TypeScript compatible. I assume there is a problem with your compiler settings. I recommend taking a look at [the test repository](https://github.com/jeffreylanters/react-unity-webgl-test).

**Comment by michaelcuneo** [comment]
Compiler Settings of the Unity project?

**Comment by michaelcuneo** [comment]
All I did to make this error was git clone both react-unity-webgl-test rename the include in react-unity-webgl-test for the react-unity-webg limport to point to an actual import instead of a .tgz. npm install. Then npm start.

**Comment by michaelcuneo** [comment]
https://haldor.michaelcuneo.com.au:3001/ ... this is it running live, straight from the cloned code, with zero changes.

**Comment by michaelcuneo** [comment]
It turns out that this dev environment doesn't function to find the files, so it gave these errors, if I run npm run build, I can see a Unity project in my window, with the test version, rb 4.0.0 won't allow me to see the files in dev, so I must run npm run build first, then look, now that it does find the files, it has different errors.

Uncaught (in promise) TypeError: window.createUnityInstance is not a function

**Comment by motiondirector** [comment]
I'm getting same error even after `npm run build`. I'm using React.version 16.13.1

**Comment by jeffreylanters** [comment]
> Uncaught (in promise) TypeError: window.createUnityInstance is not a function

@michaelcuneo You've probably entered the wrong URL's to the Unity Context model. Can you check your network settings to see if these files are loaded correctly?

> I'm getting same error: UnityContext is not a constructor even after npm run build. I'm using React.version 16.13.1.
@motiondirector Are you sure you've imported the class correctly? Can you `console.log(typeof UnityContext)` to verify this.

**Comment by motiondirector** [comment]
@jeffreylanters Thanks! I'm using ^7.1.10 version with Unity 2019 WebGL build. Resolved by using `UnityContent` instead of `UnityContext`.
