### ISSUE TITLE
Unity Config with .unityweb extensions

### ISSUE THREAD

**Issue by damianhadji** [elraccoone/react-unity-webgl#127]
Hi Jeffrey,

My unity build for WebGL / Assembly outputs files with .unityweb extensions.

Does your library support this?

Do I need to add some sort of web.config to my react client to parse the .unityweb files?

Here is what I attempted, where the build folder is in the public folder:

```
function App() {
  let unityContext = new UnityContext({
    loaderUrl: "build/UnityLoader.js",
    dataUrl: "build/Builds.data.unityweb",
    frameworkUrl: "build/Builds.wasm.framework.unityweb",
    codeUrl: "build/Builds.wasm.code.unityweb",
  });

  return <Unity unityContext={unityContext} />;
}
```

All I can see is a warning:

unity.ts:80 Something went wrong while mouting the UnityInstance TypeError: window.createUnityInstance is not a function
    at Unity.<anonymous> (unity.ts:73)
    at step (PropTypes.js:11)
    at Object.next (PropTypes.js:11)
    at fulfilled (PropTypes.js:11)

Appreciate any help you could provide.

Thanks

Damian

**Comment by jeffreylanters** [comment]
Hi. Which version of Unity did you use to create this build?

**Comment by damianhadji** [comment]
2019.4.12f1

I initially tried version @7.* and got this error:
TypeError: react_unity_webgl__WEBPACK_IMPORTED_MODULE_4__.UnityContext is not a constructor

Then I tried upgrading to @8.* and got what I mentioned above.

**Comment by jeffreylanters** [comment]
I recommend using TypeScript for type-safe auto completion and validation. 
Also see [the Readme for 7.x](https://github.com/elraccoone/react-unity-webgl/tree/7.1.10), UnityContext was refactored to UnityContent.
Here is some [example code from the old Wiki](https://github.com/elraccoone/react-unity-webgl/wiki/Quick-Start-Guide/d8e7405fc4d759633a8b9eed8659ff9df83a35f7).
When possible try upgrading your project to Unity 2020 for the best WebGL support.

**Comment by damianhadji** [comment]
That is working now, thanks for your help!

**Comment by davevanfleet** [comment]
Hi there! I'm having this issue, too, and I don't quite understand the resolution.  Is there a setting in the Unity build that should be changed? Or is it something in React? (Sorry I'm more of a React dev on my team with extremely little Unity experience)

**Comment by davevanfleet** [comment]
Disregard! We were on Unity 2019 (I thought it was 2020). Changing the React component that renders the game to Typescript and switching to version 7.x using the instructions in the README you mentioned was all I needed.  @jeffreylanters I suspect I'll be using this project quite a bit, if there's any (relatively easy) bug fixes, changes, or improvements that need to be made I'm more than willing to help.

**Comment by zalven** [comment]
Not yet though. I'm kinda hard for me to solve it because it's not my
forte. I have experience with react but not in unity, Sorry about that.
Please message or email me if you already solved it. Thank you!
