### ISSUE TITLE
Unable to locate the loader files

### ISSUE THREAD

**Issue by nipundavid** [elraccoone/react-unity-webgl#130]
After the export to WebGL from my Unit3d project I am not able to locate the files as mentioned in the helper code
```

  loaderUrl: "build/myunityapp.loader.js",
  dataUrl: "build/myunityapp.data",
  frameworkUrl: "build/myunityapp.framework.js",
  codeUrl: "build/myunityapp.wasm",
```

My export has files - 
![Capture](https://user-images.githubusercontent.com/2108309/97905819-ab240180-1d68-11eb-8122-8d4e9b9d977b.PNG)

I mean yeah there is loader but the data is missing and so does the .wasm file. Am I using the right version of npm package?

and also since I am using function components I hope this syntax would work
```
{
const [unityContext, setUnityContext] = useState(null);
useEffect(() => {
    document.body.classList.toggle("profile-page");

    setUnityContext(
      new UnityContext({
        loaderUrl: "/ColorJump3D/Build/UnityLoader.js",
        dataUrl: "/ColorJump3D/Build/build.data",
        frameworkUrl: "build/myunityapp.framework.js",
        codeUrl: "build/myunityapp.wasm",
      })
    );
  }, []);
```

```
 return (
<div className="wrapper">
 <Container>
              <Unity unityContext={unityContext} />
  </Container>
      </div>
)
```

this code should work as well, right? if I get the above thing sorted
I am using Unity3D 2019

regards,
Nipun David

**Comment by jeffreylanters** [comment]
Hi Nipun, this seem like a duplicate of #127 - can you check this issue since it might solve your problem.

**Comment by nipundavid** [comment]
Hi Jeff thanks, this helped and now I can see my game 

cheers
