### ISSUE TITLE
Custom event listener receives a wrong parameter if var type is not int

### ISSUE THREAD

**Issue by simentesempre** [elraccoone/react-unity-webgl#138]
**Describe the bug**
We are receiving some data from Unity, while listening to a OnPlayerDeath event, but the payload we're receiving in React isn't right when we use a type other than int

**To Reproduce**
1. Create the method in C# 
![WhatsApp Image 2020-12-30 at 21 01 54](https://user-images.githubusercontent.com/7099936/103379223-3a3d6380-4ae5-11eb-8d02-593724cc9619.jpeg)
2. Creates the string with the method 
![WhatsApp Image 2020-12-30 at 21 02 29](https://user-images.githubusercontent.com/7099936/103379246-54774180-4ae5-11eb-8de7-64385e2e93da.jpeg)
3. Creates the bridge 
![WhatsApp Image 2020-12-30 at 21 03 14](https://user-images.githubusercontent.com/7099936/103379263-62c55d80-4ae5-11eb-821f-b3cd8bc8053a.jpeg)
4. Listens to the event in React

```
unityContent.on('OnPlayerDeath', (payload) => { 
    console.log(payload, typeof payload)
    const [score, ...awardsCollected] = payload.split(",")
    setShowRestart(true)
    setScore(score)
    const awardsUpdated = { ...awardsObject }
    Object.keys(awardsObject).forEach( (key, i) => {
      awardsUpdated[key].taken =  awardsCollected[i]
    })
    setAwards(awardsUpdated)
})
```

**Expected behavior**
The expected output of the console.log should be a string similar to this "34,0,1,1,0,0" followed by the type of the var, "string"

**Actual behaviour**
The output of the console.log is 
60803920 "number"

The value of the parameter on the other hand is correctly passed if instead of a string we use a integer, but we actually need to pass multiple values to that event.

**Details (please complete the following information):**
 - React Unity WebGL Version: 7.1.10
 - Device and OS:  Acer, Windows 10
 - Browser: Chrome 87.0.4280.88
 - NodeJS Version: 14.15.0
 - Bundler: Create React App

**Comment by jeffreylanters** [comment]
Hi! This is not just a number, it’s a pointer. Unity uses points to pass all non number values. You have to turn the pointer back into a string using built in methods provided by Unity.

**Comment by jeffreylanters** [comment]
```js 
mergeInto(LibraryManager.library, {

  Hello: function () {
    window.alert("Hello, world!");
  },

  HelloString: function (str) {
    window.alert(Pointer_stringify(str));
  },

  PrintFloatArray: function (array, size) {
    for(var i = 0; i < size; i++)
    console.log(HEAPF32[(array >> 2) + i]);
  },

  AddNumbers: function (x, y) {
    return x + y;
  },

  StringReturnValueFunction: function () {
    var returnStr = "bla";
    var bufferSize = lengthBytesUTF8(returnStr) + 1;
    var buffer = _malloc(bufferSize);
    stringToUTF8(returnStr, buffer, bufferSize);
    return buffer;
  },

  BindWebGLTexture: function (texture) {
    GLctx.bindTexture(GLctx.TEXTURE_2D, GL.textures[texture]);
  },

});
```

**Comment by simentesempre** [comment]
Thank you very much @jeffreylanters, our unity developer was able to succesfully update the code thanks to your answer.
Thanks, happy new year

**Comment by jeffreylanters** [comment]
Great! Best of luck with your project, and a happy year to you and your team too!
