### ISSUE TITLE
Console error when trying to use .gz or .unityweb files from Unity 2020 WebGL build

### ISSUE THREAD

**Issue by sd63534790** [elraccoone/react-unity-webgl#144]
I'm getting console error below when trying to use .gz or .unityweb  files:
This is how I'm trying to use them in UnityContext constructor.
const WEBGL_BUILD = 'webGL_build_unity2020';

...
 const sourcePath = `${process.env.baseBuildPath ? '/' + process.env.baseBuildPath : '..'}`
 const unityContext = new UnityContext({
  loaderUrl: `${sourcePath}/WebglSource/PublishTest/PublishTest.loader.js`,
  dataUrl: `${sourcePath}/WebglSource/PublishTest/PublishTest.data.unityweb`,
  frameworkUrl: `${sourcePath}/WebglSource/PublishTest/PublishTest.framework.js.unityweb`,
  codeUrl: `${sourcePath}/WebglSource/PublishTest/PublishTest.wasm.unityweb`,
});
...
Can I use .gz or .unityweb  files on UnityContext if having the server configured for gzip compression? Will it be slow if compression is not supported?

**Comment by jeffreylanters** [comment]
Hi, this is off-topic. GZipping has to be configured on your server.

**Comment by sd63534790** [comment]
Thank you.If server support, Can I wirte code like this?
const unityContext = new UnityContext({
loaderUrl: ${sourcePath}/WebglSource/PublishTest/PublishTest.loader.js,
dataUrl: ${sourcePath}/WebglSource/PublishTest/PublishTest.data.gz,
frameworkUrl: ${sourcePath}/WebglSource/PublishTest/PublishTest.framework.js.gz,
codeUrl: ${sourcePath}/WebglSource/PublishTest/PublishTest.wasm.g,
});

**Comment by jeffreylanters** [comment]
No problem. If your browser supports it, yes!

**Comment by sd63534790** [comment]
I set nginx gzip and application/wasm type, But it didn't work.I'm getting console error below when trying to use .gz files:
`webGL_build_unity2020.framework.js.gz:1 Uncaught SyntaxError: Invalid or unexpected token`
`BigScene.loader.js:1 Uncaught ReferenceError: unityFramework is not defined`
Please help me.
![1611884343(1)](https://user-images.githubusercontent.com/5291257/106220259-11101000-6216-11eb-8a55-1187c92a6efc.png)

**Comment by jeffreylanters** [comment]
Sorry, this has nothing to do with the mode, I cannot help you with this. You might want to head over to [Unity's documentation](https://docs.unity3d.com/Manual/webgl-deploying.html), it's not focussed on NGINX but might help you none the less.

**Comment by sd63534790** [comment]
The server is configured,But has no effect.Does anyone have the same problem?Loading with uncompressed files is too slow,7.X version is well supported.
