### ISSUE TITLE
Previous version documentation

### ISSUE THREAD

**Issue by DaviesCooper** [elraccoone/react-unity-webgl#148]
The documentation for react-unity-webgl version 8.x is great. However, all links to documentation for all previous version points to the wiki which no longer documents the older versions.

Because of this, I don't know what features are available from older versions, nor how to properly configure anything.

**Comment by jeffreylanters** [comment]
Hi! It's not the best solution, but you can dive back into older versions of the documentation.

**Comment by DaviesCooper** [comment]
> Hi! It's not the best solution, but you can dive back into older versions of the documentation.

Yeah I definitely tried haha. Apart from the quick-start sections, all older documentation provides links to the wiki. The issue with this is that the wiki is not current. Unless I am missing some way to see previous versions of the wiki?

**Comment by jeffreylanters** [comment]
You're referring to the readme in the repository, right? The Wiki itself is just like a repository, is has its own [commit history](https://github.com/elraccoone/react-unity-webgl/wiki/_history). But it is still, not the best solution. I hope this helps!

**Comment by jeffreylanters** [comment]
By the way, the link above is the history of all the pages combined. Each page has its own list of commits, which can be found by clicking on the "x revisions" text on the top of the page. I little bit of a hidden feature by GitHub imo.

**Comment by DaviesCooper** [comment]
Oh wow this is EXACTLY what I was looking for. You're definitely right that this appears very hidden haha. Thanks a ton!

**Comment by jeffreylanters** [comment]
No problem, best of luck with your project!

**Comment by blakerunyon09** [comment]
Hey @jeffreylanters I've been looking forever but can't find any legacy docs. Where are these located?

**Comment by jeffreylanters** [comment]
Hi, sorry for the confusion. The documentation has been moved over to [its respective version tag](https://github.com/jeffreylanters/react-unity-webgl/tree/7.1.13#readme). I hope this helps you, happy coding.
