### ISSUE TITLE
Unable to work with Typescript?

### ISSUE THREAD

**Issue by DaviesCooper** [elraccoone/react-unity-webgl#151]
I am unable to get react-unity-webgl  V7.1.10 to work in a typescript framework.

I get a Type Error specifying that ReactUnityWebGL.\<my function\> is not a function when using the following jslib in unity

```
mergeInto(LibraryManager.library, {

    SendJSONMessageToPortal: function(text) {
        ReactUnityWebGL.<My function>(Pointer_stringify(text));
    }
});
```

I know the issue is specifically related to this because if I change the jslib to the following

```
mergeInto(LibraryManager.library, {

    SendJSONMessageToPortal: function(text) {
        console.log(Pointer_stringify(text));
    }
});
```
The webGL build loads fine and outputs whatever message is meant to be sent.

I think the issue has to do with lazy evaluation of the function associated with the ReactUnityWebGL object, which I'm not sure if it assigns the function name in a type-safe way. I could also just be talking out of my ass.

**Comment by DaviesCooper** [comment]
Ok i was able to fix this by manipulating the window similar to how you do in the constructor. Rather than call the unity contents on method, I directly assign the function I need with the appropriate callback.
(window as any).ReactUnityWebGL = { <My event name>: (message: string) => <My callback>(message) };

I'm suuuuper new to react so any feedback on exactly how bad of a practice this is would be appreciated haha.

**Comment by jeffreylanters** [comment]
Hi! I'm a little confused by your problem. Since the JSLib never sees, goes through or has even anything to do the TypeScript compiler?

I personally never ran into this problem, and did not see a similar issue pass by. Is it possible to share more details and perhaps some code so I can help you further. Thanks!

**Comment by jeffreylanters** [comment]
Issue closed due to inactivity
