### ISSUE TITLE
Module not working in Azure Production environment

### ISSUE THREAD

**Issue by danbugs** [elraccoone/react-unity-webgl#164]
**Describe the bug & Expected Behavior & Screenshots**
Embedding the game works fine in localhost but not when deployed to Azure.

Working on localhost:
![localhost](https://i.imgur.com/5joOdOa.png)

Not working on deployed site:
![Azure](https://i.imgur.com/DONvVhw.png)

My version of Unity is 2020.1.17f1 so I'm using one of the latest versions of this dependency.

**To Reproduce**
1. Create a React application.
2. Create a Development Unity WebGL build inside a folder called Build.
3. Add Build folder (inside of the other Build folder we just created) w/ `Build.data`, `Build.framework.js`, `Build.Loader.js`, and `Build.wasm` to your React app's public folder.
4. In your React app, before your component definition, add:
```javascript
import Unity, { UnityContext } from "react-unity-webgl";

const unityContext = new UnityContext({
  loaderUrl: "Build/Build.loader.js",
  dataUrl: "Build/Build.data",
  frameworkUrl: "Build/Build.framework.js",
  codeUrl: "Build/Build.wasm",
});
```
... and, in your `render` method, add:
```html
<Unity unityContext={unityContext} />
```
5. Run locally.
6. Get no errors.
7. Deploy to Azure.
8. Get errors.

**Details:**
 - React Unity WebGL Version: 8.0.3
 - Device and OS: Computer w/ Windows 10
 - Browser: Screenshots are from Edge but I tried other browsers too and got the same result.
 - NodeJS Version: 12.20.1
 - Bundler: Created a ReactJS app w/ an ASP.NET back-end. The ASP.NET back-end serves the front-end.

**Additional context**
It worked initially but after some update (can't recall which), it simply stopped.

**Comment by jeffreylanters** [comment]
This problem seems to be unrelated to this module, but rather has something to do with web assembly. [ref1](https://www.reddit.com/r/Unity2D/comments/9xwy8q/whats_the_webgl_error_still_waiting_on_run/) [ref2](https://github.com/emscripten-core/emscripten/issues/13326)
