### ISSUE TITLE
Error while creating the Unity Instance Error: Unable to invoke Unity Loader, loaded incorrectly.

### ISSUE THREAD

**Issue by mattdeitke** [elraccoone/react-unity-webgl#167]
**Describe the bug**

I'm getting the following error: `Error while creating the Unity Instance Error: Unable to invoke Unity Loader, loaded incorrectly`. I've added a minimal reproducible example to [GitHub here](https://github.com/mattdeitke/react-unity-webgl-issue).

The WebGL player works and loads fine by starting a local server from `static/demo`, but I haven't had any success getting it to work from `react-unity-webgl`.

The rendered code for react-unity-webgl is [in this file](https://github.com/mattdeitke/react-unity-webgl-issue/blob/master/src/pages/index.tsx), which simply does
```tsx
import React from "react"
import Unity, { UnityContext } from "react-unity-webgl"

const unityContext = new UnityContext({
  loaderUrl: "/demo/Build/UnityLoader.js",
  dataUrl: "/demo/Build/game.data.unityweb",
  frameworkUrl: "/demo/Build/game.wasm.framework.unityweb",
  codeUrl: "/demo/Build/game.wasm.code.unityweb",
})

export default function Home() {
  return (
    <div>
      <h1>This page has loaded!</h1>
      <Unity unityContext={unityContext} />
    </div>
  )
}
```
which only renders the header, ignoring the Unity tag due to the error invoking Unity Loader.

![image](https://user-images.githubusercontent.com/28768645/110715338-e40e3000-81b9-11eb-9ec7-4437cf822c7d.png)

> Note that `demo/Build` appears in the repo's `static` folder, which then renders in the root of the site via Gatsby. So `static/demo/Build/game.json` appears in the path `www.hostname/demo/Build/game.json`. So, there does not appear to be any errors with the path names. (I have also tried changing `/demo/Build/...` to `demo/Build/...` (i.e., removing the leading `/`), but it still fails in the same way.

For reference, here is approximately what it looks like when running locally by starting a local-server in `static/demo`:
![image](https://user-images.githubusercontent.com/28768645/110715469-259edb00-81ba-11eb-94e1-67af2ae61c87.png)

Notice that it is successful without any problems.

**To Reproduce**

1. Clone https://github.com/mattdeitke/react-unity-webgl-issue
2. Install yarn
3. Run it locally via `yarn run develop`

**Expected behavior**

`react-unity-webgl` loads the WebGL player in the same way that starting a local server from `static/demo` loads the Unity WebGL player perfectly.

**Screenshots**

![image](https://user-images.githubusercontent.com/28768645/110721298-1d986880-81c5-11eb-80b8-4910467fa911.png)

**Details (please complete the following information):**
 - React Unity WebGL Version: 8.X
 - Device and OS: Windows 10
 - Browser: Tested on FireFox and Chrome
 - NodeJS Version: 14.15.4

**Comment by mattdeitke** [comment]
Good news: It looks like it works when switching to Unity WebGL Version 7.X. I thought I was exporting from Unity 2020, but I was still using 2019.4.20F. Thanks for the awesome package :)

**Comment by jeffreylanters** [comment]
Awesome! Best of luck with your project!
