### ISSUE TITLE
Unity to React communication example

### ISSUE THREAD

**Issue by firststef** [elraccoone/react-unity-webgl#171]
**Is your feature request related to a problem? Please describe.**
I searched for about 1 hour about _malloc, writeStringToMemory, and others and I didn't understand a thing from the paragraph in the current documentation. Until I found this [Unity page](https://docs.unity3d.com/530/Documentation/Manual/webgl-interactingwithbrowserscripting.html) which had the same explanation, but I found on this page an example that helped me understand how to convert strings into javascript.

**Describe the solution you'd like**
It would be very nice to add their example at least:

---

#### Example

```jsx
mergeInto(LibraryManager.library, {
  Hello: function()
  {
    console.log("Hello, world!");
  },
  HelloString: function(str)
  {
    console.log(Pointer_stringify(str));
  },
  PrintFloatArray: function(array, size)
  {
    for(var i=0;i<size;i++)
      console.log(HEAPF32[(array>>2)+size]);
  },
  AddNumbers: function(x,y)
  {
    return x + y;
  },
  StringReturnValueFunction: function()
  {
    var returnStr = "bla";
    var buffer = _malloc(lengthBytesUTF8(returnStr) + 1);
    writeStringToMemory(returnStr, buffer);
    return buffer;
  },
  BindWebGLTexture: function(texture)
  {
    GLctx.bindTexture(GLctx.TEXTURE_2D, GL.textures[texture]);
  }
});
```

---

**Comment by jeffreylanters** [comment]
Hi! This is a good suggestion, I'll update the read-me a soon as possible!

**Comment by jeffreylanters** [comment]
I've updated the [documentation](https://github.com/elraccoone/react-unity-webgl#example-implementation-16), thanks for your suggestion. I think this is a good addition!
