### ISSUE TITLE
Unity 2020.3.2f1 doesen't recieve messages

### ISSUE THREAD

**Issue by SpadaccinoIgnorante** [elraccoone/react-unity-webgl#172]
i am using your react library to interact with my unity application, but also with a simple test is not working, i suppose is a compatibility issue.

this is the line of code to send the message to unity : unityContent.send(“MyObject”,”TestMethod”,true);
of course in unity there is a gameobject called “MyObject” and a script with a public method called TestMethod(bool value);
 
The react library version is the latest (8.3.1) and i can see the page with my application, but i cannot interact it trough react.
 
// React code
unityContent.send("MyObject","TestMethod",true);

C# Code 
` public class TestReact : MonoBehaviour
{
    public void TestMethod(bool test)
    {
        Debug.Log($"Test message {test}");
        Camera.main.backgroundColor = Color.blue;
    }
}`

**Comment by invlabz** [comment]
@SpadaccinoIgnorante Hey, I am facing same issue. How did you solve this?
