### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by manzinge** [elraccoone/react-unity-webgl#175]
**Describe the bug**
When I load the Unity Files (not compressed) through the UntiyContext I get the Error "RangeError: Offset is outside the bounds of the DataView" with the loader.js File (loaderUrl). All of the files are loading properly and the mime-Types are correct.

I already had the Plugin working with Unity 2019 and the 7.x Version of the Package.
**To Reproduce**
1. Create an uncompressed Unity Build
2. Setup the Basic Example
3. Run the Basic Sample
4. Receive an error

**Expected behavior**
The Game should start up as always.

**Screenshots**
![image](https://user-images.githubusercontent.com/43249083/113458418-751ba400-9412-11eb-8fa7-e1c85b4eebc8.png)
![image](https://user-images.githubusercontent.com/43249083/113458491-b613b880-9412-11eb-99bf-b8188361cbf5.png)

**Details (please complete the following information):**
 - React Unity WebGL Version: [8.2.0]
 - Device and OS: [Win 10, Android, everything]
 - Browser: [Edge Dev, Edge, Chrome, Firefox]
 - NodeJS Version: [14.16.0]

Best
Max

**Comment by manzinge** [comment]
Wow, how embarrasing!
My data File was encoded as text/html instead of octet-stream therefore it didn't work!

Leaving this in case anyone else has the same problem.

Best
Max

**Comment by SimonMorkSaetre** [comment]
How did you solve it? I am unable to figure out how you converted the data file.

**Comment by manzinge** [comment]
@SimonMorkSaetre 
Hey there, as statet in the comment below the error was the file encoding.

**Comment by SimonMorkSaetre** [comment]
I am aware, but where can one change the file encoding? 'm storing the files in the public folder.
