### ISSUE TITLE
Responsive canvas size

### ISSUE THREAD

**Issue by ray-su** [elraccoone/react-unity-webgl#47]
the <canvas> element will only stay at initial width and height and not able to change them afterward.

I am trying to set the canvas width and height dynamically when browser window size changes: 
`<Unity
          unityContent={this.unityContent}
          className="unityApp"
          height={this.props.browserWindow.height}
          width={this.props.browserWindow.width}
        />`

**Describe the solution you'd like**
Make it listen to the height and width props, and change canvas size accordingly

**Comment by jeffreylanters** [comment]
If you have binded your props to a state, the height and width should update. I'm not sure if Unity resizes the player according to the container. Have you tried using a width and height of `100%` and using that to scale the player relative to it's parent element or the container?

**Comment by ray-su** [comment]
OR, Is there any responsive size related setting on the Unity end?
I'm not  a Unity developer, so I'm not too familiar with it.

**Comment by jeffreylanters** [comment]
I'm sorry, this has to be something with your project. I've just cloned the test environment and simply set the width to 100% and height 100vh and it worked as expected. But I did notice it won't adjust when I resize the window, so I will take a look at that en fix it. Can you share your code?

**Comment by jeffreylanters** [comment]
The most simple implementation of a completely fullscreen Unity player would looks something like:

```jsx
<div
  style={{
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%"
  }}
>
  <Unity unityContent={this.unityContent} width="100%" height="100%" />
</div>
```

**Comment by ray-su** [comment]
Sorry, my narrative skill sucks lol.  
What I am trying to achieve is to make it adjust when resizing the window. Not just fullscreen when it first loaded.

**Comment by jeffreylanters** [comment]
Give me 10 more minutes to finish and I'll publish `7.0.6` on NPM 😄

**Comment by jeffreylanters** [comment]
I've released patch `[7.0.6](https://github.com/jeffreylanters/react-unity-webgl/releases/tag/7.0.6)`. Please see the [wiki](
https://github.com/jeffreylanters/react-unity-webgl/wiki/Unity-Config#adjust-on-window-resize) for more details. Let me know if this patch fixes your problem. :)

**Comment by ray-su** [comment]
Perfect. Thank you!  Let me try it now

**Comment by ray-su** [comment]
😔    Unfortunately, It's not working.   Please see screenshot below.

![resized](https://user-images.githubusercontent.com/14828286/42836627-8d8d2776-89c9-11e8-8d55-386f4001619f.PNG)

The width and height of the <canvas> did change,  but the content inside the canvas did not.  


Does it work for you?  If so, then there might be problem with my Unity WebGl build

**Comment by jeffreylanters** [comment]
That’s odd. It’s working perfect for me... I have no control over the canvas itself, Unity takes it over from there.  There’s nothing more I can do, there might be some problems with your build.

**Comment by ray-su** [comment]
Ya, that's what i thought.  Let me figure it out with my Unity dev.
Thank you for your help.

**Comment by ray-su** [comment]
Ok, I just tested it with this Unity build, https://greggman.github.io/better-unity-webgl-template/.
And it works perfectly. So I can confirm it is my Unity build's problem.

**Comment by jeffreylanters** [comment]
Let’s see. What’s your Unity version. Are you using post processing?

**Comment by ray-su** [comment]
we are using 2018.1.1f1,  and using unity's standard post processing

**Comment by ray-su** [comment]
Ok, our Unity dev confirmed that it is a bug from Unity. 
It is related to some floating point calculations.

**Comment by jeffreylanters** [comment]
Typically unity... I’m going to leave this issue open, so we can keep each other and other people who are facing this problem informed about this problem and possible fixes.

**Comment by mtebele** [comment]
Hi! I'm having exactly the same problem. When I try the Unity component in a smaller device, it cuts the game.

**Comment by jeffreylanters** [comment]
This problem only occurs if you resize your window after the initialisation of Unity. Can you please show me a screenshot of your DOM tree? @mtebele

**Comment by khandevtooth** [comment]
Hi.  I read your resolvation. And I apply it's code.
But, I experience one problem.
i execute unity in web, 
![image](https://user-images.githubusercontent.com/43776534/50264732-4656ab00-045f-11e9-9b3e-dd601c8fd9e3.png)

**Comment by jeffreylanters** [comment]
@khandevtooth It's a Unity bug. But Unity 2018.3 has been released recently. I'll check out if there are any fixes I can apply.

**Comment by rivertam** [comment]
This is a total hack, but the workaround I'm using is basically this:

```js
function resizeCanvas({ width, height }: { width: number, height: number }) {
  const canvas = document.getElementById('#canvas'); // It seems Unity makes a canvas with an id of `#canvas`. That's not a typo.
  canvas.width = width;
  canvas.height = height;
}
```

I'm no expert by any means, but this seems to be working just fine for our usecases. I think the engine is built to handle resizes of the canvas; it's just failing to update the size when asked.

I believe the `#canvas` id is set by Unity itself, but it might be our Unity engineer. Not 100%. Look through your own DOM tree if you want to be sure.

Make sure to run this after Unity has loaded. We have a waiter similar to [this guy](https://www.npmjs.com/package/async-wait-until) that doesn't allow the above to be called until `#canvas` shows up. YMMV, just thought I'd share what works for us.

**Comment by jayenashar** [comment]
while `adjustOnWindowResize` on resize is working fine for me.  i want to also be able to trigger a resize.  it may be worth documenting `adjustCanvasToContainer()`.  i use it like this:

            <Unity unityContent={this.unityContent}
                   height="100%"
                   width="100%"
                   ref={component => this.component = component} />

and later:

            this.component.adjustCanvasToContainer()

**Comment by sg3s** [comment]
On Unity version `2018.3.11f1`, without enabling the resizing functionality as provided by the plugin, we were able to get the resolution to adjust by setting the canvas element to 100% dimensions in css.

The canvas width/height are set to exact pixel values on every frame by UnityLoader, after getting the width/height needed based on its parent. You cannot directly set css width/height on the canvas, but an indirect css declaration targeting the canvas does work;

    #game-container canvas {
        width: 100% !important;
        height: 100% !important;
    }

Assuming `#game-container` is a position relative or absolute block level element and resizes with content on the page or the window itself the canvas should resize with it.

This also prevents issues when you take into account values such as `window.devicePixelRatio` to adjust to high DPI devices during frame resolution calculation.

**Comment by ray-su** [comment]
@sg3s  Thank you!

@jeffreylanters 
Yes, they finally fixed it in version 2018.3. 
 I just tested and confirm it is working with @sg3s  's solution.

**Comment by DevonTomatoSandwich** [comment]
I still had to use @sg3s solution.
I was using a uni computer though so maybe its unity version was last updated pre 2019. 
I can't check the version because i cant get in the lab because of covid lol.

if anyone comes across this issue and is a bit of a noob like me, the 
`game-container`
can be used on the parent element like
```
return (<div id="game-container">
  <Unity unityContent={unityContent} />
</div>);
```

**Comment by jeffreylanters** [comment]
@DevonTomatoSandwich I would like to implement this in a future release. Can you confirm this works _with_ and _without_ the use of the `adjustOnWindowResize` option?

**Comment by DevonTomatoSandwich** [comment]
@jeffreylanters do you mean like how it is on the [wiki](https://github.com/elraccoone/react-unity-webgl/wiki/Unity-Config#adjust-on-window-resize)? 
I tried that by adding `adjustOnWindowResize: true` like in the link and removed my `game-container` id.
but it stopped working. So i switched back to using the `game-container` id as it works for me

**Comment by jeffreylanters** [comment]
When using ReactUnityWebGL 8.0.0 for Unity 2020 resizing should work without any problem because Unity no longer creates the canvas by itself.
