### ISSUE TITLE
How to refresh unity heat memory ?

### ISSUE THREAD

**Issue by shaojianwei** [elraccoone/react-unity-webgl#53]
Hi, I'm using react-unity-webgl. Recently I got a issue, may not related to the depository, that troubles me. I have a page which loads unity. If I call `history.push(pathname)` but not `window.location.reload(true)` then, 
the unity heat memory double in size when back to this unity page . It seems the previous memory leak. Can you tell me how to solve this problem ? Thank you!

**Comment by bretlinne** [comment]
I'm not sure why I got this question.  I don't administer the repo you're
asking about.  You should find one of the devs and ask them.

**Comment by jeffreylanters** [comment]
@shaojianwei there are some problems with unloading Unity which cannot be solved at the moment due to the infrastructure of Unity. I've had contact with the devs at Unity Technologies, but they've told me there is no way to unload Unity from the memory at the moment. They'll keep me updated. You can read more about this issue here [Component doesn't unmount properly #22](https://github.com/elraccoone/react-unity-webgl/issues/22). #22

**Comment by shaojianwei** [comment]
> @shaojianwei there are some problems with unloading Unity which cannot be solved at the moment due to the infrastructure of Unity. I've had contact with the devs at Unity Technologies, but they've told me there is no way to unload Unity from the memory at the moment. They'll keep me updated. You can read more about this issue here [Component doesn't unmount properly](https://github.com/elraccoone/react-unity-webgl/issues/22) #

> @shaojianwei there are some problems with unloading Unity which cannot be solved at the moment due to the infrastructure of Unity. I've had contact with the devs at Unity Technologies, but they've told me there is no way to unload Unity from the memory at the moment. They'll keep me updated. You can read more about this issue here [Component doesn't unmount properly](https://github.com/elraccoone/react-unity-webgl/issues/22) #22.

Thanks for your patience!

**Comment by the-halfbloodprince** [comment]
are these problems solved yet? It's been almost 6 years

**Comment by jeffreylanters** [comment]
> are these problems solved yet? It's been almost 6 years

Partially, this issue were Unity is unable to properly unmount is still present. However, a method to unload Unity from memory has been added to the module. See the documentation for more details. 

https://react-unity-webgl.dev/docs/api/unload
