### ISSUE TITLE
Passing more than one argument with send method.

### ISSUE THREAD

**Issue by vavonvavo** [elraccoone/react-unity-webgl#56]
Hey. It would be great to add opportunity to send more than one argument with `send` function.

**Describe the solution you'd like**
Sending arguments as third, fourth etc of `send` function parameters or array of arguments.

**Comment by jeffreylanters** [comment]
Haha.. I see @AlezM just forked my repo to implement this! @AlezM, would you like to contribute your changes?

**Comment by vavonvavo** [comment]
I just saw it. But what's about not fixed number of arguments to pass?

**Comment by AlezM** [comment]
@jeffreylanters Hello! I'm not really a TypeScript programmer, I tried to send two arguments, but finally, we think that it would be great if you help us to make it more flexible))

**Comment by jeffreylanters** [comment]
That is fine, thank you! I'll look into it tomorrow.

**Comment by vavonvavo** [comment]
Yup, I didn't notice that. I guess we can close this issue then.
