### ISSUE TITLE
Error loading Unity content

### ISSUE THREAD

**Issue by HHammerite** [elraccoone/react-unity-webgl#57]
I'm not sure if this is something with React itself or the package. I get this in the browser console when trying to load my Unity game
`JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I've tested the same build outside of React and it loads without an issue. 
Any help would be appreciated. My Unity version is 2018.3.1f1

- Apologies if this is obvious. I've only just started to use React in the last few days.

**Comment by HHammerite** [comment]
Perfect! It works! I was placing the build inside my src folder... Thank you for your help!

**Comment by Syndicist** [comment]
The issue I made (referenced directly above) was marked as a duplicate of this one - though, my filesystem was exactly as described as the above, which is why I made a new issue about it. I realized under more scrutiny, that the index.html built from unity was actually conflicting with the index.html being used for react. Though the error disappeared, the unity project still isn't rendering.
![image](https://user-images.githubusercontent.com/31106886/75688519-a0f7b380-5c6d-11ea-8ea9-aa38de4e3d83.png)

**Comment by RazrSlyr** [comment]
I am having this same issue and I was wondering if anyone could assist me here. As far as i understand my file structure matches what is being asked but I am still getting the error. This is what I have.

unityContext:
![image](https://user-images.githubusercontent.com/22282254/148334144-e43cc362-f446-406b-bfae-8872e0fad235.png)

location of build:
![image](https://user-images.githubusercontent.com/22282254/148334198-12f329b5-8c6b-4f32-89d4-2159a73e850b.png)

The build being in the same folder as the index.html should mean that this should work but I am still getting the error. Any assistance would be greatly appreciated.

**Comment by jeffreylanters** [comment]
Are you able lief voor the JavaScript file from the browser? @RazrSlyr

**Comment by RazrSlyr** [comment]
Do you mean through the sources tab in Inspect Element? If so, no. None of the JS files show up in the sources.

**Comment by jeffreylanters** [comment]
No, I meant if you are able to view the file using the browser in a new tab. To confirm if the file is reachable as a public URL.

**Comment by RazrSlyr** [comment]
Oh okay that makes more sense. I was able to access the files through the browser in the form of a url.
![image](https://user-images.githubusercontent.com/22282254/148413585-fa19039a-6026-4d3d-a18d-b8d5e90e3df8.png)

**Comment by RazrSlyr** [comment]
Okay I was able to fix the issue. I had to add "workshop/" to the beginning of all my paths for the unityContext.
![image](https://user-images.githubusercontent.com/22282254/148417351-8cb6ff36-2aa5-4cf9-868d-7d84c1ca6b1e.png)

**Comment by studentofcoding** [comment]
Hello @jeffreylanters, I've had similar problems with @RazrSlyr, but right now it's still a blank screen 😢 

<img width="1440" alt="Screen Shot 2022-04-06 at 10 12 47" src="https://user-images.githubusercontent.com/20473526/161888680-32b138a7-c86d-4b67-987b-7000e5278edc.png">

I've set the dir to match what you have @RazrSlyr, but still no luck and this error of `Uncaught SyntaxError: Unexpected token '<' (at DEMO_1.loader.js:1:1)` keep appearing

Much appreciate if you can help with this!
