### ISSUE TITLE
Override Error.handler for UnityLoader

### ISSUE THREAD

**Issue by bartofzo** [elraccoone/react-unity-webgl#64]
Hi,

First of all thanks for this component, I've been using it without any problems for my game. I have a feature request. Would it be possible to override the Error.handler function on the UnityLoader object?

As described in this thread:
https://forum.unity.com/threads/make-javascript-errors-not-alert-in-5-6.466772/

 I've tried to edit the source in Unity.ts here:
` this.unityContent.setUnityInstance(UnityLoader.instantiate(
        `__ReactUnityWebGL_${this.props.unityContent.uniqueID}__`,
        this.props.unityContent.buildJsonPath, {
          onProgress: this.onProgress.bind(this),
          Module: this.props.unityContent.unityConfig.modules,
          width: "100%",
          height: "100%"
        }));
      }`

But UnityLoader has no Error object here and I have zero experience in TypeScript myself. Would this be hard to implement?

Thanks.

**Comment by jeffreylanters** [comment]
Hey! Sorry for this late response. -- I'm glad I'm not the only way being annoyed by this, I've made an implementation for this about a year ago, but removed it due to instability. The solution you've referenced seems pretty simple and efficient. I will implement this as soon as possible, probably next Tuesday. Are you willing to help me test?

**Comment by bartofzo** [comment]
Thanks. Yes I'll test it.

I've already found a temp solution by editing Unity.js and adding this line:

UnityLoader.Error.handler = (e) => console.log(e);

just before  _this.unityContent.setUnityInstance...

So it should be a simple thing to implement.

**Comment by jeffreylanters** [comment]
Thanks for doing the research, that helps me a lot. I'll implement it right now!

**Comment by jeffreylanters** [comment]
I've added an event listener too, so you can catch the error yourself too.
https://github.com/elraccoone/react-unity-webgl/wiki/Communication-Unity-on-Error

**Comment by jeffreylanters** [comment]
Check out release [7.1.5](https://github.com/elraccoone/react-unity-webgl/releases/tag/7.1.5)

**Comment by bartofzo** [comment]
Looks good! The error handler has 2 parameters though, the second I believe is module. I'm not using it but maybe it would be good to include it in your definition for people that want to use it.

**Comment by jeffreylanters** [comment]
Thanks! I'll add it later.

**Comment by zaneclaes** [comment]
@jeffreylanters does this feature still exist? I can't find any documentation on error handling with the current version. I'm trying to suppress the javascript error box popup that breaks the game in the case of any uncaught exception =/
