### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Fallc** [elraccoone/react-unity-webgl#67]
Hi,

sorry it's another post regarding setup errors. I can't seem to get it going. I setup a project using create-react-app and a unity build. The unity build is working fine standalone. When I try to incorporate it into my react application, all I'm getting is a grey screen and errors. Even when I build the application using npm run build and serve the app from a static server, I get the same error.

I placed the unity files in the public folder like this: 

```
|- index.html
|- Tetris
      |- Build.json
      |- UnityLoader.js

```
And the react file:

```
import React from "react";
import Unity, { UnityContent } from "react-unity-webgl";

class App extends React.Component {
  constructor(props) {
    super(props);

    // Next up create a new Unity Content object to 
    // initialise and define your WebGL build. The 
    // paths are relative from your index file.

    this.unityContent = new UnityContent(
      "Tetris/Build.json",
      "Tetris/UnityLoader.js"
    );
  }
  render() {

    // Finally render the Unity component and pass 
    // the Unity content through the props.

    return <Unity unityContent={this.unityContent} />;
  }
}

export default App;
```

And the error messages:

<img width="1440" alt="Bildschirmfoto 2019-06-24 um 22 09 27" src="https://user-images.githubusercontent.com/22775549/60048618-cf7bc280-96cc-11e9-9e18-474b4dd2de44.png">

And the resources in Chrome:

<img width="226" alt="Bildschirmfoto 2019-06-25 um 00 22 40" src="https://user-images.githubusercontent.com/22775549/60055904-6cdff200-96df-11e9-9d4e-73498dc6ed07.png">

Do you maybe have a running example I could clone and see where I'm going wrong?

Any help is appreciated!

**Comment by jeffreylanters** [comment]
I've been looking at your screenshots for a while now, I can't really tell what it going on. It looks like the Unity Loader was loaded successfully, but the Unity Loader was unable to load the blob. As seen in the screenshot below.

![image](https://user-images.githubusercontent.com/3404617/60081233-ae00f200-9731-11e9-9604-4dfebea7b11e.png)

Two thing we could do, you might want to share you source. Or you can try the get [react-unity-webgl-test](https://github.com/jeffreylanters/react-unity-webgl-test) to run. -- Let me know!

**Comment by jeffreylanters** [comment]
This might be it, I see you webserver is hosted on port 5000. But I see the Unity Loader is attempted to load from port 64194.

![image](https://user-images.githubusercontent.com/3404617/60081636-734b8980-9732-11e9-99fe-825c8ad41c14.png)

**Comment by Fallc** [comment]
Hi,

the second screenshot was from another test on a different port. Apologies for the confusion.

Anyway, when I manually go to the mentioned URL, I get this:

<img width="1440" alt="Bildschirmfoto 2019-06-25 um 12 42 23" src="https://user-images.githubusercontent.com/22775549/60092221-c4657880-9746-11e9-9b77-2cf56a343ec9.png">
 
The connection to the file seems to be working, but I somehow get nothing, just this:

<img width="1440" alt="Bildschirmfoto 2019-06-25 um 12 45 12" src="https://user-images.githubusercontent.com/22775549/60092354-1c03e400-9747-11e9-8469-d04f5c63b96a.png">

Here is a link to the repo:
https://github.com/Fallc/canu-tetris-test

I've also deployed this stripped-down version on Heroku:
https://tetris-standalone.herokuapp.com/

**Comment by Fallc** [comment]
I got it know, I missed the .unityweb files as in your example project. Thank you for your help and your module!
