### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by Fabi42** [elraccoone/react-unity-webgl#73]
I'm using react-unity-webgl v7.1.7
It used to work perfectly, but now when I want to import a new Unity WebGL Build, I'm getting this error:
Json.parse: unexpected character at line 1 column 1 of the JSON data
![image](https://user-images.githubusercontent.com/26481224/61534018-bc8bb200-aa2e-11e9-944e-341436f97bca.png)
Obviously there is a Syntax error in JSON.parse in UnityLoader.js, which I cannot find...
And this prevents building the whole unity WebGl.

However, when I run the Unity-WebGl-Build in it's build folder, it is running perfectly.
(I do this with npm's http-server on the build folder for the webgl Unity Project.)

### Maybe related?
I've seen this problem on a  [Unity Forum](https://answers.unity.com/questions/1334307/unexpected-character-at-line-1-column-1-of-the-jso.html), but I don't think that this applies to my case, since I'm running it on localhost using a Mac. But it might be related?
However I tried to create a web.config file in my src and build folder of the react app. The error persists.

The Unity Version of the WebGL build is 2019.1 and I also tried 2019.3 - but this cannot be the matter, since it worked before...

Any ideas?!

**Comment by jeffreylanters** [comment]
Looks like a duplicate of #57

**Comment by Fabi42** [comment]
Sorry, my bad. I was changing the assets in the build folder... Thanks for the quick help!
