### ISSUE TITLE
String gets trimmed on communication to react from unity.

### ISSUE THREAD

**Issue by SherikarRohith** [elraccoone/react-unity-webgl#82]
i am trying to send Base64 string from unity to react but observed that the string is trimmed somewhere in the middle of the communication from unity to react.Tested it out by logging the output of both unity and react before sending from unity and after receiving it in react

**Comment by jeffreylanters** [comment]
Hello, your problem seems unrelated to this module. It looks like a limitation by Unity. You can try sending your data in smaller blobs.
