### ISSUE TITLE
Unity component doesn't use preloaded wasm files after it is unmounted 

### ISSUE THREAD

**Issue by panpan31415** [elraccoone/react-unity-webgl#84]
**Describe the bug**
the Unity component doesn't use pre-loaded wasm files after it is unmounted

I was trying to use <link rel="preload" href="wasm_file" as="fetch" /> to pre-load some unity files,so our app can load faster.  for the first time, it does use loaded files. but when you run the game at second time, borrower started download the same file again from our server.  

**To Reproduce**
1. add <link rel="preload" herf="wasm_files" as="fetch"/> to react project
2. reload the page, go to network panel in browser console. you should see browser has downloaded wasm_files before you turn on the unity game. 
3. turn on the unity game, it will run without waiting for download. 
4. after the game is finished, you can start again, you will see browser start download the wasm_files again 

**Expected behavior**
Browser should not download wasm_files unnecessary. 

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chromei]
 - Version [79.0.3945.117]

**Additional context**

**Comment by panpan31415** [comment]
an work around is we don't un-mount the unity component. we use css display property to control whether it should show or not.

**Comment by MuhammadAli-208** [comment]
Can not perform any action on reactApp when unity component loads.
