### ISSUE TITLE
Despite the right path: Unable to use the Unity Loader, please make sure you've imported the Unity Loader the correct way.

### ISSUE THREAD

**Issue by paullam328** [elraccoone/react-unity-webgl#86]
```
import React, { Component } from 'react';
import { Button, Form, FormControl } from "react-bootstrap";
// Be sure to include styles at some point, probably during your bootstraping
import '@trendmicro/react-sidenav/dist/react-sidenav.css';
import 'font-awesome/css/font-awesome.min.css';
import Unity, { UnityContent } from "react-unity-webgl";

class B extends Component {
    constructor(props) {
        super(props);
        this.unityContent = new UnityContent(
            "MyGame/SB.json",
            "MyGame/UnityLoader.js"
        )
    }

    render() {
        return (
            <Unity unityContent={this.unityContent} />
        );
    }
}

export default B;
```

index.js:1 Unable to use the Unity Loader, please make sure you've imported the Unity Loader the correct way. You might have entered an incorrect path to the UnityLoader.js. The path is not relative to your bundle, but to your index html file. See the follow link for more details:  https://github.com/elraccoone/react-unity-webgl/issues/31 error doc

I am sure my path is correct, why is it not loading?

Update 1 :
I then saw the warning:
backend.js:6 Your version of Unity does not support unloading the WebGL Player. This preverts ReactUnityWebGL from unmounting this component properly. Please consider updating to Unity 2019.1 or newer, or reload the page to free the WebGL Player from the memory. See the follow link for more details: https://github.com/elraccoone/react-unity-webgl/issues/22 
    in Building (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (at App.js:74)
    in App (at src/​index.js:8)

But whattt I am using Unity 2019.2.17f1, does this mean the loader does not support newer versions?

Update 2:
UnityLoader works without React, so it's probably not my version's problem?  But I cannot load it probably via html in my React app, since the compiler probably respects the React architecture.  It would really help if this can be solved.

Update 3:
I tried to create a new react app, and then install react-unity-webgl plugin and make it as minimalistic as possible to test.  Still, the same error pops-up, which proves it's not about my previous app.

**Comment by paullam328** [comment]
I then saw the warning:
backend.js:6 Your version of Unity does not support unloading the WebGL Player. This preverts ReactUnityWebGL from unmounting this component properly. Please consider updating to Unity 2019.1 or newer, or reload the page to free the WebGL Player from the memory. See the follow link for more details: https://github.com/elraccoone/react-unity-webgl/issues/22 
    in Building (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (at App.js:74)
    in App (at src/​index.js:8)

But whattt I am using Unity 2019.2.17f1

**Comment by paullam328** [comment]
Issue resolved.  After putting tons of log statement in this node modules for some intensive debugging, I found out I need to put my files in the public/ folder instead of src/ folder...

**Comment by nyngwang** [comment]
@paullam328: This saved me!

**Comment by SanderSpaas** [comment]
> Issue resolved. After putting tons of log statement in this node modules for some intensive debugging, I found out I need to put my files in the public/ folder instead of src/ folder...

I am working with Svelte, putting the files in the static folder instead of src/folder worked for me too. Thanks so much.
