### ISSUE TITLE
Is loading bar (aka. UnityProgress) implemented yet?

### ISSUE THREAD

**Issue by paullam328** [elraccoone/react-unity-webgl#87]
**Is your feature request related to a problem? Please describe.**
Without loading bar, the end-user will think the game window is broken due to lacking of UI/UX.

**Describe the solution you'd like**
Pre-game Loading bar would be cool

**Comment by jeffreylanters** [comment]
A graphical interface is not the purpose of this module. You can create your own loading bar using the [On Progress](https://github.com/elraccoone/react-unity-webgl/wiki/Communication-Unity-on-Progress) and [On Loaded](https://github.com/elraccoone/react-unity-webgl/wiki/Communication-Unity-on-Loaded) event listeners.

**Comment by paullam328** [comment]
Done!  I have implemented this, and it looks sick!  For those who would like to create a loading bar, feel free to use my solution as below:

1. Put the Template Data folder in src:
2. App.js - Insert:
 .logo, .progress {position: absolute; left: 50%; top: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%);}
 .logo {background: url('../TemplateData/progressLogo.Light.png') no-repeat center / contain; width: 154px; height: 130px;}
.progress {height: 18px; width: 141px; margin-top: 90px;}
.progress .empty {background: url('../TemplateData/progressEmpty.Light.png') no-repeat left / cover; float: right; width: 100%; height: 100%; display: inline-block;}
 .progress .full {background: url('../TemplateData/progressFull.Light.png') no-repeat right / cover; float: left; width: 0%; height: 100%; display: inline-block;}

.logo.Dark {background-image: url('../TemplateData/progressLogo.Dark.png');}

.footer {margin-top: 5px; height: 38px; line-height: 38px; font-family: Helvetica, Verdana, Arial, sans-serif; font-size: 18px;}
.footer .webgl-logo, .title, .fullscreen {height: 100%; display: inline-block; background: transparent center no-repeat;}
.footer .webgl-logo {background-image: url('../TemplateData/webgl-logo.png'); width: 204px; float: left;}
.footer .title {margin-right: 10px; float: right;}
.footer .fullscreen {background-image: url('../TemplateData/fullscreen.png'); width: 38px; float: right;}
`
3. Put the Whole build folder (Build and TemplateData) in the Public folder.
4. In node_modules/react_unity_webgl:
4i. `   Unity.prototype.onProgress = function (unityInstance, progression) {
        this.unityContent.triggerUnityEvent("progress", progression);
        if (progression === 1)
            this.unityContent.triggerUnityEvent("loaded");

        if (typeof this.htmlElement !== "undefined") {
            if (!unityInstance.logo) {
                unityInstance.logo = document.createElement("div");
                unityInstance.logo.className = "logo " + unityInstance.Module.splashScreenStyle;
                unityInstance.container.appendChild(unityInstance.logo);
              }
              if (!unityInstance.progress) {    
                unityInstance.progress = document.createElement("div");
                unityInstance.progress.className = "progress " + unityInstance.Module.splashScreenStyle;
                unityInstance.progress.empty = document.createElement("div");
                unityInstance.progress.empty.className = "empty";
                unityInstance.progress.empty.style.width = "100%";
                unityInstance.progress.appendChild(unityInstance.progress.empty);
                unityInstance.progress.full = document.createElement("div");
                unityInstance.progress.full.className = "full";
                unityInstance.progress.full.style.width = "0%";
                unityInstance.progress.appendChild(unityInstance.progress.full);
                unityInstance.container.appendChild(unityInstance.progress);
              }
              unityInstance.progress.full.style.width = (100 * (1 - progression)) + "%";
              unityInstance.progress.empty.style.width = (100 * progression) + "%";
              if (progression == 1) {
                unityInstance.logo.style.display = unityInstance.progress.style.display = "none";
              } else {
                  if (unityInstance.logo && unityInstance.progress) {
                    unityInstance.logo.style.display = unityInstance.progress.style.display = "flex";
                  }
              }
        }
    };`
