### ISSUE TITLE
unable to get unity progress

### ISSUE THREAD

**Issue by vijayxd** [elraccoone/react-unity-webgl#88]
unitycontent.unityinstance is undefined untill loaded scene

but in normal javascript unityinstance = unityloader.instantiate (...). 
unityinstance returns all properties and able track progress
how to get unity progress

**Comment by jeffreylanters** [comment]
You can add an event listener to the Unity Content to track the loading progression. [You can read more about this here](https://github.com/elraccoone/react-unity-webgl/wiki/Communication-Unity-on-Progress).

```js
this.unityContent.on('progress', progression => {
  console.log(`Loaded ${progression * 100}%);
});
```

**Comment by paullam328** [comment]
Look at #87 if you wanna create a loading bar using Vanilla JS
