### ISSUE TITLE
Unity 2020.1 are making changes to WebGL builds that break this package

### ISSUE THREAD

**Issue by oleandreas86** [elraccoone/react-unity-webgl#95]
Link to their changes here: https://forum.unity.com/threads/changes-to-the-webgl-loader-and-templates-introduced-in-unity-2020-1.817698/

Basically, they are removing the .json file and integrating it directly into the index.html in their template.

Any idea on how to make this work with their 2020.1 version?

**Comment by jeffreylanters** [comment]
Hey, thanks for your message, I didn't release they planned on changing their entire system. I'll be looking into it as soon as possible, I've created an issue and branch for the log of the development #96. If you're interested in helping with the development, feel free to do so!
