### ISSUE TITLE
React Unity WebGL ErrorEvent

### ISSUE THREAD

**Issue by niddhog** [elraccoone/react-unity-webgl#98]
**Error Description**
When running the unity component on my Heroku Server, the Unity component won't load and I get the following Error Messages:

React Unity WebGL ErrorEvent
UnityLoader.Error.handler @ Unity.js:145

Uncaught SyntaxError: Unexpected token '<'

React Unity WebGL ErrorEvent
UnityLoader.Error.handler @ Unity.js:145

Uncaught ReferenceError: UnityModule is not defined
at UnityLoader.loadCode.Module (UnityLoader.js:4)
at HTMLScriptElement.i.onload (UnityLoader.js:4)

![image](https://user-images.githubusercontent.com/34284541/79379897-e8a57680-7f5f-11ea-9528-3e668fb30a4e.png)

**To Reproduce**
Please visit the following link for my Unity-React build on Heroku:
https://sopra-fs20-group-13-client.herokuapp.com/unityTesting

**Expected behavior**
I expect the unity component to run and communicate with React (and vice versa). When running it locally using npm run dev, the unity component runs flawlessly and also communicates with React and Vice Versa

**Screenshots**
Screenshot of my ReactUnityWebGL.jslib
![image](https://user-images.githubusercontent.com/34284541/79369639-92313b80-7f51-11ea-9623-ddaa9b707523.png)

I also added a web.config file (found this solution on the web), to no avail:
![image](https://user-images.githubusercontent.com/34284541/79369695-ab39ec80-7f51-11ea-9ecb-e6bd4a4ca640.png)

Here is my linking to UnityLoader.js and Build.json, which should be right as far as I can see it:
![image](https://user-images.githubusercontent.com/34284541/79382218-79318600-7f63-11ea-9088-eabe46a0e998.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge, Safari
 - Unity Version 2019.3.9f1

**Additional context**
I have spend all day trying to fix this but I am at my ends wits. Any help is highly appreciated

**Comment by niddhog** [comment]
Solved… had to change build.json to Build.json *facepalm*

**Comment by jeffreylanters** [comment]
Glad you've solved it, thanks anyway for your detailed explanation, I appreciate it! Good luck with your project!
